### ISSUE TITLE
Macros.type PSTR example in readme.md

### ISSUE THREAD

**Issue by leavesofgrass** [keyboardio/Kaleidoscope-Macros#12]
The readme example includes:

`Macros.type(PSTR("Hello "), PSTR("world!"));
`

This doesn't compile but a single PSTR does work:

`Macros.type(PSTR("Hello world!"));`

**Comment by algernon** [comment]
I can't reproduce this... is your `Arduino-Boards` repo up to date? In earlier versions of the `Kaleidoscope-Macros` library we used to have a `Macros.type()` that only took a single argument, the one that takes a variadic number is reasonably recent (merged about a week ago).

**Comment by leavesofgrass** [comment]
My boards repo was updated this morning. The example in the readme is different than that found in https://github.com/keyboardio/Kaleidoscope/blob/master/examples/Kaleidoscope/Kaleidoscope.ino which does build.

I'm going to keep tinkering because I can't seem to get any modified or additional macros to compile properly.

**Comment by algernon** [comment]
Weird. I tried the example in the README, and it did compile. Did you also run `git submodule update` in the boards repo? Just updating the repo will not update the submodules.

**Comment by leavesofgrass** [comment]
I just went back and updated the submodules and gave the example another try but it's still not building.

Here is the sketch:

https://gist.github.com/leavesofgrass/7ac87fa0ec495ff428ba077349660cb2

Here is the compiler output:

https://gist.github.com/leavesofgrass/e835a0803088c7121c5be8bd19013b7c

**Comment by leavesofgrass** [comment]
I started fresh. New clones of the repos and a new IDE install and everything is working properly now with the `Macros.type(PSTR("Hello "), PSTR("world!"));`

And `Macros.type(PSTR("Hello world!"));` still works too.
