### ISSUE TITLE
Record Macros at runtime

### ISSUE THREAD

**Issue by theSloopJohnB** [keyboardio/Kaleidoscope-Macros#13]
Would it be possible to record macros at runtime?

From the example in the README.md it looks like all macros need to be compiled. Software like vim lets you record macros on the fly for temporary use. This would be handy for a physical device. You could hit a button to record, type a few things, hit a button to stop the recording. Then, you can hit a button to play back the macro.

Is this possible?

**Comment by algernon** [comment]
This is not something that can be done right now, but such a feature is planned.

We first have to teach the plugin to be able to work with macros stored in EEPROM (#3), a part of the hardware that is writable without reflashing, and survives unplugging the keyboard (unlike its built-in memory). The recording feature can then be built upon that foundation.

We are not quite there yet, mind you.

**Comment by cdisselkoen** [comment]
I disagree with the fundamental assumption that runtime/dynamic macros require macro storage in EEPROM.  In 99% of my envisioned use cases (for example, my use cases of Vim's macros feature), any macros I record I only use for ~a couple minutes after recording, max - and never across reboots.  I would find great utility even from a runtime/dynamic macros feature that was based in SRAM, even though these macros wouldn't survive the keyboard's loss of power.

Therefore, it is my great pleasure to introduce [Kaleidoscope-MacrosOnTheFly](https://github.com/cdisselkoen/Kaleidoscope-MacrosOnTheFly), a dynamic-macros plugin for Kaleidoscope.  This plugin definitely works, and has been tested a little, but it's still somewhat a work in progress - has a few known limitations that need ironing out.  Nonetheless, feedback / feature requests / ideas / contributions are all very welcome!

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#369.
