### ISSUE TITLE
Wait times above 256ms don't work

### ISSUE THREAD

**Issue by SimonWoolf** [keyboardio/Kaleidoscope-Macros#16]
Hi :)

Specifying a wait time higher than 256ms results in a series of compiler warnings, and the wait is not effective -- e.g. specifying 10000ms results in an actual wait of about 15ms (as measured by xev).

Warnings:
```
$ make flash
BOARD_HARDWARE_PATH="/home/simon/Arduino/hardware" /home/simon/Arduino/hardware/keyboardio/avr/libraries/Kaleidoscope/bin//kaleidoscope-builder flash
Building output/Model01-Firmware/Model01-Firmware (0.0.0-gv1.22-5-g9503-dirty) ...
In file included from /home/simon/Arduino/hardware/keyboardio/avr/libraries/Kaleidoscope-Macros/src/Kaleidoscope-Macros.h:6:0,
                 from /mnt/terra/home/simon/Arduino/Model01-Firmware/Model01-Firmware.ino:23:
/mnt/terra/home/simon/Arduino/Model01-Firmware/Model01-Firmware.ino: In function 'const macro_t* macroAction(uint8_t, uint8_t)':
/home/simon/Arduino/hardware/keyboardio/avr/libraries/Kaleidoscope-Macros/src/MacroSteps.h:21:91: warning: narrowing conversion of '257' from 'int' to 'const macro_t {aka const unsigned char}' inside { } [-Wnarrowing]
 #define MACRO(...) ({static const macro_t __m[] PROGMEM = { __VA_ARGS__, MACRO_ACTION_END }; &__m[0]; })
                                                                                           ^
/home/simon/Arduino/hardware/keyboardio/avr/libraries/Kaleidoscope-Macros/src/MacroSteps.h:22:50: note: in expansion of macro 'MACRO'
 #define MACRODOWN(...) (keyToggledOn(keyState) ? MACRO(__VA_ARGS__) : MACRO_NONE)
                                                  ^
/mnt/terra/home/simon/Arduino/Model01-Firmware/Model01-Firmware.ino:235:12: note: in expansion of macro 'MACRODOWN'
     return MACRODOWN(D(LeftAlt), D(Sysreq),
            ^
/home/simon/Arduino/hardware/keyboardio/avr/libraries/Kaleidoscope-Macros/src/MacroSteps.h:21:91: warning: large integer implicitly truncated to unsigned type [-Woverflow]
 #define MACRO(...) ({static const macro_t __m[] PROGMEM = { __VA_ARGS__, MACRO_ACTION_END }; &__m[0]; })
                                                                                           ^
/home/simon/Arduino/hardware/keyboardio/avr/libraries/Kaleidoscope-Macros/src/MacroSteps.h:22:50: note: in expansion of macro 'MACRO'
 #define MACRODOWN(...) (keyToggledOn(keyState) ? MACRO(__VA_ARGS__) : MACRO_NONE)
                                                  ^
/mnt/terra/home/simon/Arduino/Model01-Firmware/Model01-Firmware.ino:235:12: note: in expansion of macro 'MACRODOWN'
     return MACRODOWN(D(LeftAlt), D(Sysreq),
            ^
^C/home/simon/Arduino/hardware/keyboardio/avr/build-tools/makefiles//rules.mk:75: recipe for target 'flash' failed
make: *** [flash] Interrupt
```

(Context: I'm trying to make a macro to easily do alt-sysrq-<something> key combinations, so was trying the following: `MACRODOWN(D(LeftAlt), D(Sysreq), W(1000), U(LeftAlt), U(Sysreq));`, with the idea that I'd press some other key during the 1s delay. If the answer is that this is the wrong way to go about this, that's fine, and any suggestions on better way would be greatly appreciated (I tried kaleidoscope-oneshot, but it doesn't support sysrq used as a modifier). Thanks in advance!)

**Comment by gedankenexperimenter** [comment]
The value is stored in a single byte, so there are only 256 possible values. It's possible to change those values so it's not in milliseconds (e.g. multiply by some power of ten, or change to a non-linear scale), because it calls `delay()`, which takes a 32-bit integer (in milliseconds) as its argument.

However, that won't get you what you want, because `delay()` stops the processing of the program, so if you use a 10-second `delay()`, any keys pressed during that time will be ignored, and nothing will be sent to the host, either.

**Comment by gedankenexperimenter** [comment]
It would be possible to do what you want (basically making an arbitrary `OneShot` key), but it's much more involved than just allowing bigger wait times.

**Comment by SimonWoolf** [comment]
Ah, I see. Thanks for the explanation @gedankenexperimenter ! I'll close this issue and explore other options (maybe have a go at hacking on OneShot at some point). Cheers

**Comment by gedankenexperimenter** [comment]
I'm not familiar enough with the code here, but it may be possible to do what you want using a fully-custom macro without any changes to the plugin. I just don't know if the function will get called when the key isn't pressed.

**Comment by gedankenexperimenter** [comment]
I think it can be done; it looks like `*macroAction` will get called on the cycle after the keyswitch turns off (i.e. `keyWasPressed`), so what you need is to set a timeout using `millis()` so that processing doesn't stop, and keep injecting both the macro key and the `alt`+`sysrq` until that timer runs out. Set the expiry time (`millis() + timeout`) when `keyToggledOn` is true, and on each subsequent cycle compare that to `millis()`, and when it's past, stop injecting the keycodes. For this to work, the expiry time needs to be declared `static` (I think) in your `macroAction` function, so its vaule is preserved from one cycle to the next.

**Comment by cdisselkoen** [comment]
I think you can also do exactly what you want with jamesnvc's [Kaleidoscope-PrefixLayer](https://github.com/jamesnvc/Kaleidoscope-PrefixLayer).

**Comment by gedankenexperimenter** [comment]
In fact, it's simpler than I thought, and very similar to the default firmware's `anyKeyMacro`:

```
// Experimental OneShot macro
static void oneShotMacro(uint8_t keyState) {
  uint32_t timeout = 1000;
  static uint32_t end_time = 0;

  if (keyToggledOn(keyState)) {
    end_time = millis() + timeout;
  }

  if (millis() < end_time) {
    kaleidoscope::hid::pressKey(Key_LeftShift);
    kaleidoscope::hid::pressKey(Key_LeftControl);
  }
}
```
That's not really a `OneShot`, because it stays active until the timeout expires, but pretty close, and it would give you what you want (substituting `alt` & `sysrq` for the modifiers I used).

**Comment by SimonWoolf** [comment]
Thanks @gedankenexperimenter ! That works a treat -- incorporated into my layout as https://github.com/SimonWoolf/Model01-Firmware/commit/0c7829b379cd86aec4a62c600b431edb87e6eb28 .

(FWIW, after some experimentation, turns out that the `Key_Sysreq` code doesn't seem to be recognised by linux as a sysrq -- xev was showing it as `NoSymbol`, with or without alt. But alt+printscreen does work).

I'm struggling to understand why it works, though -- in particular, why the macro continues to be called on every cycle until the timeout expires. I'm guessing `handleMacroEvent` is being called by the synthetic keypresses from the `pressKey` calls, which passes it on to `macroAction` despite the lack of `IS_MACRO` because of the `SYNTHETIC` flag. But it invokes `macroAction` with the keyCode of the `mappedKey`, which would be the keyCode of leftalt or printscreen -- but `macroAction` has to be being invoked with that macro's enum'd constant, else it wouldn't dispatch to the right clause of the switch statement. So I'm misunderstanding something about this.

(That's just for my curiosity, though -- the actual problem's solved, so many thanks for that!)

**Comment by gedankenexperimenter** [comment]
I'm also not clear on why this works without continuing to use `pressKey` for the macro key, too. Perhaps @cdisselkoen or @algernon can enlighten us…

**Comment by algernon** [comment]
> I'm struggling to understand why it works, though -- in particular, why the macro continues to be called on every cycle until the timeout expires.

It gets called because we call event handlers every cycle, for every key, even if they have not been pressed. Precisely for these use cases, where you want the key to do something when tapped, and continue doing it even if released. And this is why a lot of macros use `keyToggledOn` or `keyIsPressed` to do their thing - so they don't do it when the key is idle.

Does this make things clearer?

**Comment by gedankenexperimenter** [comment]
I knew that, but I had failed to trace the path through the code correctly. For some reason, I was starting from `readKeyCodeAndPlay()` instead of `handleMacroEvent()`. The former stops if the keyswitch wasn't active in either the current or the previous cycle. Reading it correctly now, it's clear.

**Comment by SimonWoolf** [comment]
> Does this make things clearer?

Much clearer, thanks for the explanation.
