### ISSUE TITLE
Unable to type backtick (`) with macros

### ISSUE THREAD

**Issue by nikitakit** [keyboardio/Kaleidoscope-Macros#17]
Steps to reproduce:
* Add some backticks (`) to the BUILD_INFORMATION string in the default firmware
* Flash the keyboard, and have it report version info

Expected behavior: information string is printed with backticks intact
Observed behavior: backticks are removed from the string, but other symbols are kept

Of course, my actual usecase is to have backticks in a real macro rather than just the build info. Am I missing something here? I'm on OSX and just cloned all the repositories today, if that matters.

(And thank you for making such a wonderful keyboard!)

**Comment by gedankenexperimenter** [comment]
I just submitted a pull request that should fix this

**Comment by algernon** [comment]
My bad, the problematic code is my work. Thank you @nikitakit for finding the problem, and @gedankenexperimenter for the fix. Much appreciated!
