### ISSUE TITLE
Held keys might be left out of the report when a macro plays.

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Kaleidoscope-Macros#19]
If a macro key is handled before a held modifier in the scan order, the modifier won't be in the report when the macro plays. I believe the simplest solution is to not play the macro during the event handler hook, but wait until the pre-report hook.

**Comment by algernon** [comment]
Running them in the pre-report hook sounds like a good idea. We'll need to keep track of which macros to run, though. I suppose a 32-bit bitmap should work fine initially? Or should we go with 64, to be on the safer side?

**Comment by gedankenexperimenter** [comment]
Or we could declare that only a certain number of macros can run concurrently, and store that number of bytes.

**Comment by algernon** [comment]
But those bytes would still be used as a bitmap, I suppose? Not sure it is worth it to abstract that away at this point. I'd just go with 32 or 64... probably 64. If that ends up being too few, we can still change the implementation without user-visible changes (apart from code size).

**Comment by gedankenexperimenter** [comment]
No, I wasn't thinking of using them as a bitmap — just storing integer (enum) values. That way we can have up to 255 macros, but only `MAX_CONCURRENT_MACROS` at a time, as opposed to up to 64 macros, and no limit on how many are active concurrently.

As it's written, is it possible to have more macros active than the number of pressed keys?

**Comment by algernon** [comment]
Oh, I see. Will have to ponder about this a bit...

Using a bitmap is memory efficient, but limiting. Using an array of ints is much less limiting, but much more costly. 8 concurrent macros is 1 byte when bitmap, 8 when an array. Come to think of it... that's not terrible. Especially if we can save memory elsewhere.

**Comment by gedankenexperimenter** [comment]
I don't think either approach is obviously superior, but if we can guarantee that at most one macro active per held key, then 64 bits would be sufficient (for the Mode01). Each bit could correspond to a key(switch), rather than a macro index. Then we just do a keymap lookup, and ignore anything that's not mapped to a macro key. (One more thing that would be easier with `active_keys_[]` instead of `liveCompositeKeymap[]`, but that's for another day).

**Comment by gedankenexperimenter** [comment]
Now that I've had a chance to sit down with the code in front of me, I see that my idea won't work – or, at least, it's much more difficult than I thought. There are three problems:

## The problems

1. Macros can use the `row` and `col` class variables, which are set by the `handleMacroEvent()` function, and only valid during the pre-report hook (if we add one) if only one macro is active at a time. This can be dealt with by using my idea for a bitfield representing the keys on the keyboard, but that's incomplete it doesn't account for injected macro keys.

2. `macroAction()` takes `keyState` as a parameter, and (typically) passes that on to macro functions. This is a problem, because there's no existing mechanism to get those key state bits from the hardware module. We could solve this problem by storing one more byte per macro.

3. Existing macro functions get called regardless of the key state, even if the key isn't pressed, and wasn't just released. Of course, if a layer change happens, a macro on the newly-activated top layer won't get called until the first time its key is pressed, because `updateLiveCompositeKeymap()` doesn't get called until a key is pressed. Furthermore, most (all?) existing macros probably just exit if the key is neither pressed nor just-released, and it would probably be reasonable to enforce that, but it would change the current interface.

I've got two solutions that I think are _maybe_ reasonable:

## Solution A

We set a limit on the number of concurrently-active macros. This seems reasonable if we consider that most macros are expected to be played only when a key is held, and most people have only ten fingers. A default value for `MAX_CONCURRENT_MACROS` could be 8.

We store three bytes per macro:
* One byte for macro index
* One byte for key index (i.e. row & col)
* One byte for key state

Then, in a pre-report hook, we call all the macro functions in the active list, setting `Macros_::row` & `Macros_::col`, and passing the recorded `keyState` along. I'm not sure what to do when we get more than `MAX_CONCURRENT_MACROS` active; my only ideas are to silently ignore the last one, or to pick one and play it right away (like I did in Qukeys when the queue gets full).

## Solution B

We use the same trick I used in [`Qukeys::flushKey()`](https://github.com/gedankenlab/Kaleidoscope-Qukeys/blob/0fa876f912294dcb031b4b2002fc1f009488d45e/src/Kaleidoscope/Qukeys.cpp#L153), where the last keyboard HID report is copied, and modifications are added on top of that, instead of using the current (incomplete) report. This has the benefit of being fairly simple (no need to add another hook function or store any additional state), but the rather big drawback of bypassing the HID façade, because it doesn't provide a mechanism for accessing the reports – so it would only work with KeyboardioHID.

Despite having devised this approach myself, I don't like it. The HID façade functionality could be extended to make it a supportable technique, but it will never be quite the right way to deal with the issue, because restoring the saved, incomplete, current report might not actually be the right thing to do after the new report(s) are sent.

## Conclusion

For now, I think Solution A is the better choice, even though it's more work, introduces a limitation that Solution B doesn't suffer from, and requires both more code and more state storage.

Long term, I think a major change to the main Kaleidoscope key scan loop is the real answer to this problem (and many others). A more detailed discussion about that solution is beyond the scope of this  issue, though.

**Comment by gedankenexperimenter** [comment]
If @algernon agrees that it makes sense, I'll create a PR for Solution A.

If I do that, the big question is whether or not to limit the macros that play. The only macros that would get called in this case would be ones with a non-zero `keyState`, which would make it possible to simplify certain macro code, but make certain other macro techniques impossible (e.g. using timers that persist after the key is released).
