### ISSUE TITLE
Key repeat broken for multi-key macros

### ISSUE THREAD

**Issue by jhurwitz** [keyboardio/Kaleidoscope-Macros#23]
[(continued from the Keyboardio Discourse)](https://community.keyboard.io/t/are-there-docs-on-key-states-keytoggledon-key-is-pressed-key-toggled-off-anywhere/890/7?u=jhurwitz)

For demonstration purposes, I've taken the default firmware (keyboardio/Model01-Firmware@11676727) and made just a single change:

```
diff --git a/Model01-Firmware.ino b/Model01-Firmware.ino
index bc45ee3..6a182e0 100644
--- a/Model01-Firmware.ino
+++ b/Model01-Firmware.ino
@@ -236,7 +236,8 @@ const macro_t *macroAction(uint8_t macroIndex, uint8_t keyState) {
     break;

   case MACRO_ANY:
-    anyKeyMacro(keyState);
+    if (keyIsPressed(keyState))
+      return MACRO(D(A));
     break;
   }
   return MACRO_NONE;
```

This works as expected. I'm on a Mac running [Key Codes](https://manytricks.com/keycodes/) to inspect keyboard inputs, and pressing the any key works identically to pressing the A key: I see a Key Down event, then a brief pause, then Key Down (Repeat) events, and finally (when I release the key) a Key Up event. I would also add that the Key Down (Repeat) events are on the order of magnitude of 10 per second.

Let's instead change this macro to: `return MACRO(D(A), D(B));`. Now I get something completely different: A Key Down event for A when I first press any, and a Key Up event for A when I release any, but in the interim, I'm getting alternating Key Down and Key Up events for B on the order of magnitude of 100 per second or more -- likely, one per scan cycle.

Now admittedly this is a contrived example, but modifier + key is significantly less contrived. If I repeat this experiment with: `return MACRO(D(LeftGui), D(A));` then I get a Modifier Change event when I press and release the any button, and then Key Down/Up events for A every cycle. And likewise, if I try `return MACRO(D(A), D(LeftGui));` then I get Key Down/Up for A when I press and release the any button, and two Modifier Change events every cycle.

Let's now try lower-level functions instead of the `MACRO` macro:
```
case MACRO_ANY:
  if (keyIsPressed(keyState)) {
    kaleidoscope::hid::pressKey(Key_LeftGui);
    kaleidoscope::hid::pressKey(Key_A);
  }
  break;
```
Suddenly this works as expected, and doesn't exhibit the one-key-down/up-per-cycle behavior. This suggests that there's an issue in the keyboardio/Kaleidoscope-Macros plugin.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#368.
