### ISSUE TITLE
Question how to create a macro useable with modifier?

### ISSUE THREAD

**Issue by alexandrenavarro** [keyboardio/Kaleidoscope-Macros#25]
Question how to create a macro useable with modifier

I created a macro like that 
return MACRODOWN(D(LeftControl), T(LeftArrow), U(LeftControl));

It works well alone but when it is associated with a modifier like shift down, the modifier is lost.
I tried MACRO and U or D but the result is weird, it executes multiple times the macros without.

Can you explain what is wrong with what I did and how to solve it please, it can be useful to add a sample when modifier can be used ?

Thanks in advance,

**Comment by alexandrenavarro** [comment]
Any answer, is the problem clear?

**Comment by obra** [comment]
Hi,

For support sort of things, please post at https://community.keyboard.io.
These bug trackers are really meant for tracking defects in the software.

Thanks!
ᐧ

**Comment by alexandrenavarro** [comment]
Ok, sorry, I will ask question on https://community.keyboard.io
